INSERT INTO USER (FIRST_NAME, LAST_NAME, BIRTH_DATE, PASSPORT, ADDRESS, EMAIL, PASSWORD, ROLE) 
VALUES ('Fedor', 'Bilev', '1996-03-16', '1234567', 'Russia, Spb', 'root', '1', 'CLIENT');

INSERT INTO TARIFF (NAME, PRICE, INFO) 
VALUES ('Black', '100', '3Gb/month, 100min/month, 100sms/month ');

INSERT INTO TARIFF (NAME, PRICE, INFO) 
VALUES ('White', '200', '10Gb/month, 300min/month, 300sms/month ');

INSERT INTO TARIFF (NAME, PRICE, INFO) 
VALUES ('Green', '300', '15Gb/month, 500min/month, 500sms/month ');

INSERT INTO CONTRACT (USER_ID, TARIFF_ID, PHONE_NUMBER, BALANCE, BLOCKED)
VALUES ('1', '2', '123456789', '300', 'NOBLOCK');