INSERT INTO ROLE (ID, NAME)
VALUES (1, 'ROLE_CLIENT');

INSERT INTO ROLE (ID, NAME)
VALUES (2, 'ROLE_ADMIN');

INSERT INTO BLOCK (ID, TYPE)
VALUES (1, 'NON');

INSERT INTO BLOCK (ID, TYPE)
VALUES (2, 'CLIENT_BLOCK');

INSERT INTO BLOCK (ID, TYPE)
VALUES (3, 'ADMIN_BLOCK');



INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, PASSPORT, ADDRESS, EMAIL, PASSWORD, ROLE_ID)
VALUES (1, 'Fedor', 'Bilev', '1996-03-16', '4016', 'Russia, Spb', 'client', '356a192b7913b04c54574d18c28d46e6395428ab', 1);

INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, PASSPORT, ADDRESS, EMAIL, PASSWORD, ROLE_ID)
VALUES (2, 'Fedor', 'Bilev', '1996-03-16', '4016', 'Russia, Spb', 'admin', '356a192b7913b04c54574d18c28d46e6395428ab', 2);



INSERT INTO TARIFF (ID, NAME, PRICE, INFO, VALID)
VALUES (1, 'Black', '100', '3Gb/month, 100min/month, 100sms/month ', true);

INSERT INTO TARIFF (ID, NAME, PRICE, INFO, VALID)
VALUES (2, 'White', '200', '10Gb/month, 300min/month, 300sms/month ', true);

INSERT INTO TARIFF (ID, NAME, PRICE, INFO, VALID)
VALUES (3, 'blocked', '200', '10Gb/month, 300min/month, 300sms/month ', false);



INSERT INTO TARIFF_OPTION (ID, NAME, PRICE, CONNECTION_PRICE, INFO, TARIFF_ID)
VALUES (1, 'Option1', '1', '1', 'info', 1);

INSERT INTO TARIFF_OPTION (ID, NAME, PRICE, CONNECTION_PRICE, INFO, TARIFF_ID)
VALUES (2, 'Option2', '1', '1', 'info', 1);

INSERT INTO TARIFF_OPTION (ID, NAME, PRICE, CONNECTION_PRICE, INFO, TARIFF_ID)
VALUES (3, 'Option3', '1', '1', 'info', 1);

INSERT INTO TARIFF_OPTION (ID, NAME, PRICE, CONNECTION_PRICE, INFO, TARIFF_ID)
VALUES (4, 'Option4', '1', '1', 'info', 1);



INSERT INTO REQUIRED_OPTIONS (FIRST_OPTION_ID, SECOND_OPTION_ID)
VALUES ('1', '2');

INSERT INTO REQUIRED_OPTIONS (FIRST_OPTION_ID, SECOND_OPTION_ID)
VALUES ('1', '3');

INSERT INTO REQUIRED_OPTIONS (FIRST_OPTION_ID, SECOND_OPTION_ID)
VALUES ('3', '4');

INSERT INTO INCOMPATIBLE_OPTIONS (FIRST_OPTION_ID, SECOND_OPTION_ID)
VALUES ('4', '2');



INSERT INTO CONTRACT (ID, USER_ID, TARIFF_ID, PHONE_NUMBER, BALANCE, BLOCK_ID)
VALUES (1, '1', '2', '911', '300', 1);



INSERT INTO CONTRACT_OPTIONS (CONTRACT_ID, OPTION_ID)
VALUES ('1', '1');

INSERT INTO BASKET (CONTRACT_ID, OPTION_ID)
VALUES ('1', '3');